version: "3.9"
services:
  jupyter:
    image: python:3.11.1
    command: jupyter server
    ports:
      - 8888:8888
    volumes:
      - /mnt/c/Users/denma/OneDrive/Projects/MongoDB:/projects
    restart: unless-stopped

  mongodb:
    image: mongo:6.0.3
    volumes: 
      - mongo_db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  streamlit:
    image: python:3.11.1
    ports:
      - 8889:8889
    command: streamlit run /projects/app.py --server.port 8889
    volumes:
      - /mnt/c/Users/denma/OneDrive/Projects/MongoDB:/projects

volumes:
  mongo_db:

